version: '3.7'

services:
  mikrotik-exporter:
    build:
      context: .
    network_mode: host
  prometheus:
    network_mode: "host"
    image: prom/prometheus:latest
    command:
    - --config.file=/config/prometheus.yml
    volumes:
     - ./config:/config:ro
