global:
  scrape_interval:     10s
  evaluation_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: mikrotik-exporter
    metrics_path: /probe
    params:
      module:
        - full
    basic_auth:
      username: netpoller
      password: f7W!H*Pu
    static_configs:
    - targets:
        - 172.23.0.1
        - 172.23.0.100
        - 100.102.1.111
        - 100.102.1.112
        - 100.102.1.114
        - 100.102.1.115
        - 100.102.1.121
        - 100.102.1.131
        - 100.102.1.141
        - 100.102.1.151
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:8728

