global:
  scrape_interval:     10s
  evaluation_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: mikrotik-exporter
    bearer_token: ZwRZm7Qe6J
    dns_sd_configs:
     - names:
       - '_mikrotik._tcp.mgmt.k-space.ee'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:3001

